### ISSUE TITLE
Why do we need start_bigquery_jobs_via_bq_apis in the sdk?

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#1]
https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L566

**Comment by mtai** [comment]
We shouldn't require Partners to hook everything up into BQ DTS during development/testing.  This is a development-only method to facilitate dev/test.  It actually takes the def of ImportedDataInfo and calls the BQ load APIs instead.

**Comment by mtai** [comment]
Changed method comment to reflect Xuejian's feedback
