### ISSUE TITLE
comment is wrong

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#2]
"urs => URIs to source files in GCS"
Seems the above comment is wrong: should be local file path instead of GCS URIs?
https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L542

**Comment by mtai** [comment]
Thanks, changing to

        uris => URIs to local files.  Wildcards are not expanded
