### ISSUE TITLE
Explaination for userCredentials

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#3]
userCredentials is not required.
If it exists, DTS will use that credential to read GCS data and write to destination dataset
Otherwise, DTS will use callers' credential to read GCS data, and use DTS service account to write to destination dataset.

https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L560

**Comment by mtai** [comment]
Thanks, removed and simplified
