### ISSUE TITLE
Add run_id and timestamp in the prefix?

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#4]
Can we add run_id and timestamp in the prefix? Because there might be multiple runs, also even one run could be delivered twice, but probably we don't want multiple threads to interfere each other.
gcs_run_prefix

https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L497

**Comment by mtai** [comment]
I'd defer that to the implementing connector.  Think of the case where a Partner may want to cache files from the same DataSource/Config.... (case of backfilling multiple days)

How strongly do you feel about requiring run_id?

**Comment by mtai** [comment]
OK, spoke with Xuejian, will incorporate run_id and timestamp as part of prefix
