### ISSUE TITLE
Is it needed to set timer to update DTS automatically?

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#5]
https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L164

I see two issues:
1) Update DTS every 1 minute per run is unnecessary
2) I would ask partners to update DTS when some progress is made, instead of using a background timer, which is more meaningful.

**Comment by mtai** [comment]
K, I don't want partners to worry about update_deadline_seconds which is why I have a background timer.

We can decrease the frequency to maybe once per 5 mins?  Do we have any scalability concerns if we had all future TransferRuns sending us 1 update a minute or 1 update every 5 mins?

**Comment by mtai** [comment]
Spoke with XJ, will keep client-side buffering BUT will remove auto-insertion of a msg if no msg is found
