### ISSUE TITLE
max_lease_duration -- can we set it to be indefinite?

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#6]
If they need more than 1 hour to process a run, then the message will be delivered again, then again and again...
https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L413

**Comment by mtai** [comment]
Yes, though to be clear, we'd also raise a TimeoutError and kill the run.  See line 168 and 187-190

These 2 methods use the same parameters so I'm not TOO worried.  To be clear though, for our EXISTING transfers, do we have TransferRuns regularly exceeding 1 hour?  I think you said even for AdWords, most finish within like 5 minutes?

**Comment by mtai** [comment]
Spoke with XJ, we will remove the TransferRun timeout feature and delegate this to Partners
