### ISSUE TITLE
Can we firstly update transfer run to running state?

### ISSUE THREAD

**Issue by panxuejian** [mtai/python-docs-samples#7]
https://github.com/mtai/python-docs-samples/blob/6996d711e07ea7edaab4bb9c71ce93f0720200d3/bigquery/transfer/partner-sdk/bq_dts/base_connector.py#L460

**Comment by mtai** [comment]
This is handled by the ManagedTransferRun context manager.  In Python, the WITH block and the __enter__ method is invoked before "def process_transfer_run" is even called

See lines 192 and specifically, line 207-213

**Comment by mtai** [comment]
Closed as this addresses XJ's concerns
